package de.tilmanschweitzer.tstlp.core.parser;

import java.util.Arrays;
import java.util.List;

import static de.tilmanschweitzer.tstlp.core.TestUtils.linesFromTomcatLogExamplesFile;

public class SharedTestData {
    public static final List<String> stuckThreadExampleWithOneStuckThread = linesFromTomcatLogExamplesFile("example-with-one-stuck-thread.log");
    public static final List<String> stuckThreadExampleWithMultipleStuckThreads = linesFromTomcatLogExamplesFile("example-with-multiple-stuck-threads.log");

    public static final List<String> expectedCodeLinesInExampleWithMultipleStuckThreads = Arrays.asList(
            "26-May-2022 02:16:31.715 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-925] (id=[201733]) has been active for [37,589] milliseconds (since [5/26/22 2:15 AM]) to serve the same request for [https://confluence.example.com/pages/viewpage.action?spaceKey=SPACE&title=TITLE] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 11:24:26.625 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1312] (id=[267161]) has been active for [34,236] milliseconds (since [5/26/22 11:23 AM]) to serve the same request for [https://confluence.example.com/display/xxx] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 11:25:46.747 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1331] (id=[278449]) has been active for [32,598] milliseconds (since [5/26/22 11:25 AM]) to serve the same request for [https://confluence.example.com/display/xxx] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 13:21:44.669 WARNING [Catalina-utility-4] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1258] (id=[254522]) has been active for [37,930] milliseconds (since [5/26/22 1:21 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 14:35:49.869 WARNING [Catalina-utility-3] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1341] (id=[289791]) has been active for [35,715] milliseconds (since [5/26/22 2:35 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 22:01:00.696 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1112] (id=[250918]) has been active for [34,539] milliseconds (since [5/26/22 10:00 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 22:58:04.220 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1281] (id=[265500]) has been active for [39,227] milliseconds (since [5/26/22 10:57 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 22:58:04.221 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1269] (id=[254533]) has been active for [39,234] milliseconds (since [5/26/22 10:57 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [2] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 23:23:25.797 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1279] (id=[265498]) has been active for [32,499] milliseconds (since [5/26/22 11:22 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.",
            "26-May-2022 23:23:25.798 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8090-exec-1266] (id=[254530]) has been active for [32,488] milliseconds (since [5/26/22 11:22 PM]) to serve the same request for [https://confluence.example.com/rest/easyevents/2.0/events/listEvents] and may be stuck (configured threshold for this StuckThreadDetectionValve is [30] seconds). There is/are [2] thread(s) in total that are monitored by this Valve and may be stuck."
    );
}
